version: '3.8'

services:

  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - tiffino-net

  # Eureka Server
  eureka-server:
    build:
      context: ./Backend/eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8990:8990"
    networks:
      - tiffino-net

  # API Gateway
  api-gateway:
    build:
      context: ./Backend/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - tiffino-net

  # User Service
  userservice:
    build:
      context: ./Backend/userservice
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8890:8080"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - tiffino-net

  # Menu Service
  menu-service:
    build:
      context: ./Backend/menu-service
      dockerfile: Dockerfile
    container_name: menu-service
    ports:
      - "8920:8080"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - tiffino-net

  # Order Service
  order-service:
    build:
      context: ./Backend/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8910:8080"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - tiffino-net

  # Delivery Service
  delivery-service:
    build:
      context: ./Backend/delivery-service
      dockerfile: Dockerfile
    container_name: delivery-service
    ports:
      - "8970:8080"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - tiffino-net

  # Payment Service
  payment-service:
    build:
      context: ./Backend/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8930:8080"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - tiffino-net

  # Loyalty Service
  loyalty-service:
    build:
      context: ./Backend/loyalty-service
      dockerfile: Dockerfile
    container_name: loyalty-service
    ports:
      - "8940:8080"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - tiffino-net

  # Notification Service
  notification-service:
    build:
      context: ./Backend/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8960:8080"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - tiffino-net

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./Frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway
    networks:
      - tiffino-net 

networks:
  tiffino-net:

volumes:
  mysql_data:


